name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Specifies the available build types (configurations), e.g. Debug, Release, RelWithDebInfo, MinSizeRel, etc.
  # https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIGURATION_TYPES.html
  CMAKE_CONFIGURATION_TYPES: "Release;Debug;RelWithDebInfo;MinSizeRel"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        config: [ Release, Debug, RelWithDebInfo, MinSizeRel ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27
        add-to-path: false
    - run: echo ${{env.ANDROID_NDK_HOME}}
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE=${{env.ANDROID_NDK_HOME}}/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=23
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }}

    - name: Package
      working-directory: ${{github.workspace}}/build
      run: cpack -C ${{ matrix.config }}
