name: Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Specifies the available build types (configurations), e.g. Debug, Release, RelWithDebInfo, MinSizeRel, etc.
  # https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIGURATION_TYPES.html
  CMAKE_CONFIGURATION_TYPES: "Release;Debug;RelWithDebInfo;MinSizeRel"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        config: [ Release, Debug, RelWithDebInfo, MinSizeRel ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Ninja Multi-Config"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --rerun-failed --output-on-failure -C ${{ matrix.config }} -T test

    - name: Package
      working-directory: ${{github.workspace}}/build
      run: cpack -C ${{ matrix.config }}
