name: iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Specifies the available build types (configurations), e.g. Debug, Release, RelWithDebInfo, MinSizeRel, etc.
  # https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIGURATION_TYPES.html
  CMAKE_CONFIGURATION_TYPES: "Release;Debug;RelWithDebInfo;MinSizeRel"

jobs:
  build:
    strategy:
      matrix:
        config: [ Release, Debug, RelWithDebInfo, MinSizeRel ]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get ios-cmake
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        # Repository owner and name. Ex: sudosubin/git-clone-action
        repository: leetal/ios-cmake
        # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
        platform: github
        # Relative path from current directory, where to clone.
        path: ios-cmake # optional


    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64 -DBUILD_SHARED_LIBS=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }}

    - name: Package
      working-directory: ${{github.workspace}}/build
      run: cpack -C ${{ matrix.config }}
